-- Additive Restaurant Specials Phase 1.1 migration. Does not modify existing special/business rows.
begin;

create table if not exists public.business_special_items (
  id bigint generated by default as identity primary key,
  special_id bigint not null references public.business_specials(id) on delete cascade,
  item_name text not null check (length(btrim(item_name)) between 1 and 160),
  description text,
  price_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists business_special_items_special_order_idx
  on public.business_special_items(special_id,sort_order,id);

create or replace function public.set_business_special_items_updated_at()
returns trigger language plpgsql set search_path=public as $$
begin new.updated_at=now(); return new; end;
$$;
drop trigger if exists business_special_items_set_updated_at on public.business_special_items;
create trigger business_special_items_set_updated_at before update on public.business_special_items
for each row execute function public.set_business_special_items_updated_at();

alter table public.business_special_items enable row level security;
drop policy if exists business_special_items_public_read on public.business_special_items;
create policy business_special_items_public_read on public.business_special_items
for select to anon using (exists(
  select 1 from public.business_specials s where s.id=special_id and s.is_active=true
));
drop policy if exists business_special_items_admin_read on public.business_special_items;
create policy business_special_items_admin_read on public.business_special_items
for select to authenticated using (exists(
  select 1 from public.business_specials s where s.id=special_id
    and public.business_specials_admin_access(s.business_id::text)
));
drop policy if exists business_special_items_admin_insert on public.business_special_items;
create policy business_special_items_admin_insert on public.business_special_items
for insert to authenticated with check (exists(
  select 1 from public.business_specials s where s.id=special_id
    and public.business_specials_admin_access(s.business_id::text)
));
drop policy if exists business_special_items_admin_update on public.business_special_items;
create policy business_special_items_admin_update on public.business_special_items
for update to authenticated using (exists(
  select 1 from public.business_specials s where s.id=special_id
    and public.business_specials_admin_access(s.business_id::text)
)) with check (exists(
  select 1 from public.business_specials s where s.id=special_id
    and public.business_specials_admin_access(s.business_id::text)
));
drop policy if exists business_special_items_admin_delete on public.business_special_items;
create policy business_special_items_admin_delete on public.business_special_items
for delete to authenticated using (exists(
  select 1 from public.business_specials s where s.id=special_id
    and public.business_specials_admin_access(s.business_id::text)
));

grant select on public.business_special_items to anon;
revoke insert,update,delete on public.business_special_items from anon;
grant select,insert,update,delete on public.business_special_items to authenticated;
grant usage,select on sequence public.business_special_items_id_seq to authenticated;
notify pgrst, 'reload schema';
commit;
