-- Additive Phase 1 migration. Review businesses.id type before Production execution.
begin;

do $$
declare business_pk_type text;
begin
  select format_type(a.atttypid,a.atttypmod) into business_pk_type
  from pg_attribute a
  where a.attrelid='public.businesses'::regclass and a.attname='id' and not a.attisdropped;
  if business_pk_type is null then raise exception 'public.businesses.id type not found'; end if;
  execute format($ddl$
    create table if not exists public.business_specials (
      id bigint generated by default as identity primary key,
      business_id %s not null references public.businesses(id) on delete cascade,
      type text not null check (type in ('lunch_special','happy_hour')),
      title text not null check (length(btrim(title)) between 1 and 160),
      description text, price_text text,
      days_of_week smallint[] not null default '{}'::smallint[],
      start_time time without time zone, end_time time without time zone,
      start_date date, end_date date, image_url text,
      is_active boolean not null default true, sort_order integer not null default 0,
      created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
      constraint business_specials_date_order check (start_date is null or end_date is null or start_date <= end_date),
      constraint business_specials_time_pair check ((start_time is null) = (end_time is null)),
      constraint business_specials_days check (days_of_week <@ array[0,1,2,3,4,5,6]::smallint[])
    )
  $ddl$,business_pk_type);
end $$;

create index if not exists business_specials_business_id_idx on public.business_specials(business_id);
create index if not exists business_specials_public_order_idx on public.business_specials(is_active, end_date, sort_order, id);

create or replace function public.set_business_specials_updated_at()
returns trigger language plpgsql set search_path=public as $$
begin new.updated_at=now(); return new; end;
$$;
drop trigger if exists business_specials_set_updated_at on public.business_specials;
create trigger business_specials_set_updated_at before update on public.business_specials
for each row execute function public.set_business_specials_updated_at();

alter table public.business_specials enable row level security;
create or replace function public.business_specials_admin_access(target_business_id text)
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare admin_role text; admin_area text;
begin
  if auth.uid() is null then return false; end if;
  if to_regclass('public.profiles') is not null then
    execute 'select role, area from public.profiles where user_id=$1 limit 1'
      into admin_role,admin_area using auth.uid();
  else
    admin_role=coalesce(auth.jwt()->'app_metadata'->>'role',auth.jwt()->'user_metadata'->>'role','');
    admin_area=coalesce(auth.jwt()->'app_metadata'->>'area',auth.jwt()->'user_metadata'->>'area','');
  end if;
  if admin_role='super_admin' then return true; end if;
  if admin_role<>'regional_editor' then return false; end if;
  if admin_area='denver' then admin_area='colorado'; end if;
  return exists(select 1 from public.businesses b where b.id::text=target_business_id and b.region=admin_area);
end;
$$;
revoke all on function public.business_specials_admin_access(text) from public,anon;
grant execute on function public.business_specials_admin_access(text) to authenticated;
drop policy if exists business_specials_public_read on public.business_specials;
create policy business_specials_public_read on public.business_specials
for select to anon using (is_active=true);
drop policy if exists business_specials_admin_read on public.business_specials;
create policy business_specials_admin_read on public.business_specials
for select to authenticated using (public.business_specials_admin_access(business_id::text));
drop policy if exists business_specials_admin_insert on public.business_specials;
create policy business_specials_admin_insert on public.business_specials
for insert to authenticated with check (public.business_specials_admin_access(business_id::text));
drop policy if exists business_specials_admin_update on public.business_specials;
create policy business_specials_admin_update on public.business_specials
for update to authenticated using (public.business_specials_admin_access(business_id::text))
with check (public.business_specials_admin_access(business_id::text));
drop policy if exists business_specials_admin_delete on public.business_specials;
create policy business_specials_admin_delete on public.business_specials
for delete to authenticated using (public.business_specials_admin_access(business_id::text));

grant select on public.business_specials to anon;
revoke insert,update,delete on public.business_specials from anon;
grant select,insert,update,delete on public.business_specials to authenticated;
grant usage,select on sequence public.business_specials_id_seq to authenticated;
notify pgrst, 'reload schema';
commit;
