-- DalTownMap V101 / Newsroom V63: 매일 AI 기사 실행 메모 지원
-- 기존 newsroom_runs 테이블을 그대로 사용하므로 별도 컬럼 추가는 필요하지 않습니다.
-- newsroom_publications가 없다면 생성하고, 관리자 읽기 권한을 보장합니다.

create table if not exists public.newsroom_publications (
  id bigint generated by default as identity primary key,
  region text not null default 'dallas',
  newsroom_item_id text not null,
  post_id text,
  published_for_date date not null,
  title text,
  source_url text,
  status text not null default 'published',
  error_message text,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create unique index if not exists newsroom_publications_region_day_uidx on public.newsroom_publications(region,published_for_date);
create unique index if not exists newsroom_publications_item_uidx on public.newsroom_publications(newsroom_item_id);
alter table public.newsroom_publications enable row level security;
drop policy if exists newsroom_publications_admin_read on public.newsroom_publications;
create policy newsroom_publications_admin_read on public.newsroom_publications
for select to authenticated using (
  exists(select 1 from public.profiles p where p.user_id=auth.uid() and p.role in ('super_admin','regional_editor'))
);

-- 최근 자동 기사 실행 메모 확인
select id,region,status,found,inserted,skipped,note,error_message,started_at,finished_at
from public.newsroom_runs
where trigger_type='daily_publish'
order by started_at desc
limit 10;
