-- DalTownMap V38.2 newsroom run log and cleanup support
create table if not exists public.newsroom_runs (
  id bigint generated by default as identity primary key,
  region text not null default 'dallas',
  trigger_type text not null default 'manual',
  status text not null default 'running',
  found integer not null default 0,
  inserted integer not null default 0,
  skipped integer not null default 0,
  cleaned integer not null default 0,
  note text,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists newsroom_runs_region_started_idx on public.newsroom_runs(region, started_at desc);
alter table public.newsroom_runs enable row level security;
drop policy if exists newsroom_runs_admin_read on public.newsroom_runs;
create policy newsroom_runs_admin_read on public.newsroom_runs for select to authenticated using (
  exists(select 1 from public.profiles p where p.user_id=auth.uid() and p.role in ('super_admin','regional_editor'))
);
-- Edge Function uses service role for insert/update.
