-- DalTownMap V56: 하루 1건 달라스 라이프 자동 게시 기록
-- Supabase SQL Editor에서 한 번 실행하세요.
create table if not exists public.newsroom_publications (
  id bigint generated by default as identity primary key,
  region text not null default 'dallas',
  newsroom_item_id text not null,
  post_id text,
  published_for_date date not null,
  title text,
  source_url text,
  status text not null default 'published',
  error_message text,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists newsroom_publications_region_day_uidx
  on public.newsroom_publications(region, published_for_date);
create unique index if not exists newsroom_publications_item_uidx
  on public.newsroom_publications(newsroom_item_id);
create index if not exists newsroom_publications_published_idx
  on public.newsroom_publications(region, published_at desc);

alter table public.newsroom_publications enable row level security;
drop policy if exists newsroom_publications_admin_read on public.newsroom_publications;
create policy newsroom_publications_admin_read on public.newsroom_publications
for select to authenticated using (
  exists(select 1 from public.profiles p where p.user_id=auth.uid() and p.role in ('super_admin','regional_editor'))
);
