begin;

create extension if not exists pgcrypto;

create table if not exists public.businesses (
  id text primary key,
  name_ko text, name_en text, name text,
  category_ko text, category text, map_category text, subcategory text,
  search_keywords text, area text, address text, phone text, website text, email text,
  image_url text, image_urls jsonb default '[]', gallery_urls jsonb default '[]',
  description text, description_images jsonb default '[]', hours text,
  monday text, tuesday text, wednesday text, thursday text, friday text, saturday text, sunday text,
  business_hours jsonb, parking text, reservation text, languages text, insurance text,
  video_url text, youtube_url text, order_url text, delivery_url text, reservation_url text,
  lat double precision, lng double precision,
  is_featured boolean default false, featured_rank integer,
  is_new boolean default false, new_rank integer,
  is_popular boolean default false, popular_rank integer,
  reservation_enabled boolean default false,
  paid_product text default 'none', paid_active boolean default false,
  paid_start_at timestamptz, paid_end_at timestamptz, paid_weight integer default 1,
  rotation_enabled boolean default true,
  promo_enabled boolean default false, promo_start_at date, promo_end_at date,
  home_fixed boolean default false, home_fixed_sort integer,
  promo_image_url text, promo_text text,
  region text not null default 'dallas', is_active boolean default true,
  rating numeric, review_count integer, google_maps_url text, google_review_url text,
  google_place_id text, list_visible boolean default true,
  created_at timestamptz not null default now()
);

create table if not exists public.business_activity (
  id bigint generated by default as identity primary key,
  business_id text not null,
  action_type text not null,
  source text, content_id text,
  region text default 'dallas',
  created_at timestamptz not null default now()
);
create index if not exists business_activity_weekly_idx
  on public.business_activity(action_type,created_at,business_id);

create table if not exists public.newsroom_settings (
  region text primary key,
  home_config jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id text primary key, business_id text, region text default 'dallas',
  title text, description text, coupon_code text, image_url text,
  start_at text, end_at text, raffle_end_at text,
  is_active boolean default true, is_published boolean default true,
  hidden boolean default false, deleted boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.posts (
  id text primary key, business_id text, region text default 'dallas',
  title text, content text, type text, subtype text,
  image_url text, image_link_url text, gallery_urls jsonb default '[]', video_url text,
  external_url text, link_label text, author_name text, address text, phone text,
  event_start_at text, event_end_at text, start_at text, end_at text,
  is_published boolean default true, is_active boolean default true,
  is_pinned boolean default false, pin_order integer,
  is_alert_notice boolean default false, alert_order integer,
  hidden boolean default false, deleted boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.banners (
  id text primary key, business_id text, business_ids jsonb default '[]', region text default 'dallas',
  title text, headline text, description text, discount_label text, benefit text,
  image_url text, link_url text, start_at text, end_at text,
  is_active boolean default true, is_published boolean default true,
  hidden boolean default false, deleted boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.dalpick (
  id text primary key, business_id text, business_ids jsonb default '[]', region text default 'dallas',
  category text, title text, headline text, description text, summary text,
  discount_label text, benefit text, image_url text, link_url text,
  start_at text, end_at text, event_start_at text, event_end_at text,
  is_active boolean default true, is_published boolean default true,
  hidden boolean default false, deleted boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.slides (
  id text primary key, business_id text, region text default 'dallas',
  promo_enabled boolean default true, home_fixed boolean default false, home_fixed_sort integer,
  promo_text text, promo_image_url text, promo_start_at text, promo_end_at text,
  video_url text, link_url text, created_at timestamptz default now()
);

create table if not exists public.business_listings (
  id text primary key, business_id text, region text default 'dallas',
  title text, description text, image_url text, gallery_urls jsonb default '[]',
  video_url text, external_url text, start_at text, end_at text,
  is_active boolean default true, is_published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.newsroom_items (
  id text primary key default gen_random_uuid()::text,
  original_title text, original_summary text, original_url text,
  ai_title text, ai_summary text, ai_content text,
  source_name text, duplicate_key text, event_data jsonb default '{}',
  status text default 'published', priority_score numeric default 0,
  suggested_destination text, destination text,
  source_published_at timestamptz, collected_at timestamptz default now(),
  draft_updated_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now(),
  region text not null default 'dallas'
);

create table if not exists public.newsroom_runs (
  id bigint generated by default as identity primary key,
  trigger_type text, region text default 'dallas', status text,
  found integer default 0, inserted integer default 0, skipped integer default 0,
  note text, error_message text,
  started_at timestamptz default now(), finished_at timestamptz
);

create table if not exists public.newsroom_publications (
  id bigint generated by default as identity primary key,
  region text not null default 'dallas', newsroom_item_id text not null,
  post_id text, published_for_date date not null,
  title text, source_url text, status text default 'published', error_message text,
  published_at timestamptz default now(), created_at timestamptz default now(),
  unique(region,published_for_date), unique(newsroom_item_id)
);

do $$
declare table_name text;
begin
  foreach table_name in array array['businesses','business_activity','newsroom_settings','coupons','posts','banners','dalpick','slides','business_listings','newsroom_items','newsroom_runs','newsroom_publications']
  loop
    execute format('alter table public.%I enable row level security',table_name);
    execute format('drop policy if exists staging_public_read on public.%I',table_name);
    execute format('create policy staging_public_read on public.%I for select to anon, authenticated using (true)',table_name);
  end loop;
end $$;

drop policy if exists staging_activity_insert on public.business_activity;
create policy staging_activity_insert on public.business_activity for insert to anon, authenticated with check (true);

commit;

-- Next apply newsroom-v64-daily-core-lock.sql as a separate migration.
