const S=require('./lib/community-security'),L=require('./lib/community-lifecycle');
exports.handler=S.handler(async event=>{
  if(event.httpMethod!=='POST')return S.response(405,{ok:false});const b=S.parse(event),region=S.text(b.region||'dallas',40),auth=await S.verifyAdmin(event,region),db=auth.db,action=S.text(b.action,40);
  if(action==='list'){let q=db.from('community_posts').select('id,region,area,category,title,body,author_name,contact_type,contact_value,video_url,video_provider,status,expires_at,cleanup_after,moderation_reason,moderation_note,sold_at,view_count,comment_count,approved_at,created_at,updated_at,community_post_images(id,image_url,sort_order)',{count:'exact'}).eq('region',region).order('created_at',{ascending:false}).range(Math.max(0,Number(b.from)||0),Math.max(0,Number(b.to)||99));if(b.status&&b.status!=='all')q=q.eq('status',b.status);const r=await q;if(r.error)throw r.error;return S.response(200,{ok:true,rows:r.data||[],count:r.count||0})}
  if(action==='comments'){const r=await db.from('community_comments').select('id,post_id,author_name,body,status,created_at').eq('post_id',b.post_id).order('created_at');if(r.error)throw r.error;return S.response(200,{ok:true,rows:r.data||[]})}
  const post=await db.from('community_posts').select('id,region,category,status,created_at,expires_at,cleanup_after').eq('id',b.id).single();if(post.error)throw Object.assign(new Error('Not found.'),{status:404});if(auth.role==='regional_editor'&&post.data.region!==auth.area)throw Object.assign(new Error('Forbidden region.'),{status:403});
  if(action==='status'){const status=S.text(b.status,20);if(!['approved','rejected','deleted','expired','hidden'].includes(status))throw Object.assign(new Error('Invalid status.'),{status:400});if(status==='approved'&&!['pending','hidden'].includes(post.data.status))throw Object.assign(new Error('Invalid approval transition.'),{status:400});const changes=L.adminStatusChanges(post.data,status);if(status==='hidden'){const reason=S.text(b.reason,40),note=S.text(b.note,501);if(!['abuse','personal_info','off_topic','promotion','duplicate','other'].includes(reason)||note.length>500)throw Object.assign(new Error('숨김 사유를 선택해 주세요.'),{status:400});changes.moderation_reason=reason;changes.moderation_note=note||null}else if(status==='approved'){changes.moderation_reason=null;changes.moderation_note=null}const r=await db.from('community_posts').update(changes).eq('id',b.id).eq('status',post.data.status).select('id');if(r.error)throw r.error;if(r.data?.length!==1)throw Object.assign(new Error('게시글 상태가 변경되었습니다. 다시 확인해 주세요.'),{status:409});return S.response(200,{ok:true})}
  if(action==='category'){if(post.data.status==='hidden')throw Object.assign(new Error('숨김 글의 카테고리는 작성자 재검토 과정에서만 변경할 수 있습니다.'),{status:400});if(!S.CATEGORIES.has(b.category))throw Object.assign(new Error('Invalid category.'),{status:400});const video=['marketplace','housing'].includes(b.category)?{}:{video_url:null,video_provider:null};const r=await db.from('community_posts').update({category:b.category,...video}).eq('id',b.id);if(r.error)throw r.error;return S.response(200,{ok:true})}
  if(action==='comment_status'){const r=await db.from('community_comments').update({status:['active','hidden','deleted'].includes(b.status)?b.status:'hidden'}).eq('id',b.comment_id).eq('post_id',b.id);if(r.error)throw r.error;return S.response(200,{ok:true})}
  throw Object.assign(new Error('Invalid action.'),{status:400});
});
