const S=require('./lib/community-security');
exports.handler=S.handler(async event=>{
  if(event.httpMethod!=='POST')return S.response(405,{ok:false});const b=S.parse(event),region=S.text(b.region||'dallas',40),auth=await S.verifyAdmin(event,region),db=auth.db,action=S.text(b.action,40);
  if(action==='list'){let q=db.from('community_posts').select('id,region,area,category,title,body,author_name,contact_type,contact_value,status,expires_at,cleanup_after,sold_at,view_count,comment_count,approved_at,created_at,updated_at,community_post_images(id,image_url,sort_order)',{count:'exact'}).eq('region',region).order('created_at',{ascending:false}).range(Math.max(0,Number(b.from)||0),Math.max(0,Number(b.to)||99));if(b.status&&b.status!=='all')q=q.eq('status',b.status);const r=await q;if(r.error)throw r.error;return S.response(200,{ok:true,rows:r.data||[],count:r.count||0})}
  if(action==='comments'){const r=await db.from('community_comments').select('id,post_id,author_name,body,status,created_at').eq('post_id',b.post_id).order('created_at');if(r.error)throw r.error;return S.response(200,{ok:true,rows:r.data||[]})}
  const post=await db.from('community_posts').select('id,region').eq('id',b.id).single();if(post.error)throw Object.assign(new Error('Not found.'),{status:404});if(auth.role==='regional_editor'&&post.data.region!==auth.area)throw Object.assign(new Error('Forbidden region.'),{status:403});
  if(action==='status'){const status=S.text(b.status,20);if(!['approved','rejected','deleted','expired'].includes(status))throw Object.assign(new Error('Invalid status.'),{status:400});const changes={status,approved_at:status==='approved'?new Date().toISOString():null};const r=await db.from('community_posts').update(changes).eq('id',b.id);if(r.error)throw r.error;return S.response(200,{ok:true})}
  if(action==='category'){if(!S.CATEGORIES.has(b.category))throw Object.assign(new Error('Invalid category.'),{status:400});const r=await db.from('community_posts').update({category:b.category}).eq('id',b.id);if(r.error)throw r.error;return S.response(200,{ok:true})}
  if(action==='comment_status'){const r=await db.from('community_comments').update({status:['active','hidden','deleted'].includes(b.status)?b.status:'hidden'}).eq('id',b.comment_id).eq('post_id',b.id);if(r.error)throw r.error;return S.response(200,{ok:true})}
  throw Object.assign(new Error('Invalid action.'),{status:400});
});
