-- DalTownMap DalPick table and RLS
-- Run once in Supabase SQL Editor.

create table if not exists public.dalpick (
  id bigint generated by default as identity primary key,
  region text not null default 'dallas',
  category text not null default 'recommended',
  title text not null,
  summary text,
  content text,
  business_id text,
  image_url text,
  start_at timestamptz,
  end_at timestamptz,
  priority integer not null default 0,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dalpick_region_active_idx
  on public.dalpick(region, is_active, is_featured, priority, created_at desc);

alter table public.dalpick enable row level security;

-- Public site: only published DalPick items are readable.
drop policy if exists "dalpick public read" on public.dalpick;
create policy "dalpick public read"
on public.dalpick
for select
using (is_active = true);

-- Logged-in administrators may create and edit DalPick content.
-- This follows the existing profiles(user_id, role, area) admin model.
drop policy if exists "dalpick admin insert" on public.dalpick;
create policy "dalpick admin insert"
on public.dalpick
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.role in ('super_admin', 'admin', 'regional_admin')
  )
);

drop policy if exists "dalpick admin update" on public.dalpick;
create policy "dalpick admin update"
on public.dalpick
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.role in ('super_admin', 'admin', 'regional_admin')
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.role in ('super_admin', 'admin', 'regional_admin')
  )
);

drop policy if exists "dalpick admin delete" on public.dalpick;
create policy "dalpick admin delete"
on public.dalpick
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.role in ('super_admin', 'admin', 'regional_admin')
  )
);
