'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const specials=require('../assets/restaurant-specials.js');
const active=require('../assets/active-state.js');
const pagination=require('../assets/pagination.js');
const coordinator=require('../assets/request-coordinator.js');
const home=require('../assets/home-selection.js');
const fs=require('node:fs');
const path=require('node:path');
const fixture=require('./fixtures/restaurant-specials.cjs');
const at=value=>Date.parse(value);

test('Dallas weekday is independent of UTC date',()=>assert.equal(specials.parts(at('2026-09-22T00:30:00Z')).weekday,1));
test('DST spring and fall instants map to Dallas correctly',()=>{assert.equal(specials.parts(at('2026-03-08T07:30:00Z')).dateKey,'2026-03-08');assert.equal(specials.parts(at('2026-11-01T07:30:00Z')).dateKey,'2026-11-01');});
test('start date is inclusive',()=>assert.equal(specials.calendarState({...fixture[0],start_date:'2026-09-21'},at('2026-09-21T17:00:00Z')),'active'));
test('end date is inclusive',()=>assert.equal(specials.calendarState({...fixture[0],end_date:'2026-09-21'},at('2026-09-22T04:59:59Z')),'active'));
test('immediately before and at start time',()=>{const row=fixture[0];assert.equal(specials.isActive(row,at('2026-09-21T15:59:59Z')),false);assert.equal(specials.isActive(row,at('2026-09-21T16:00:00Z')),true);});
test('immediately before and at end time',()=>{const row=fixture[0];assert.equal(specials.isActive(row,at('2026-09-21T19:29:59Z')),true);assert.equal(specials.isActive(row,at('2026-09-21T19:30:00Z')),false);});
test('overnight range uses prior weekday after midnight',()=>{const row=fixture.find(x=>x.id==='g-night');assert.equal(specials.isActive(row,at('2026-09-22T05:30:00Z')),true);assert.equal(specials.isActive(row,at('2026-09-22T06:00:00Z')),false);});
test('overnight interval may finish after its inclusive end date',()=>{const row={...fixture.find(x=>x.id==='g-night'),end_date:'2026-09-21'};assert.equal(specials.isActive(row,at('2026-09-22T05:30:00Z')),true);});
test('inactive is excluded',()=>assert.equal(specials.isDiscoverable(fixture.find(x=>x.id==='d-off'),at('2026-09-21T17:00:00Z')),false));
test('expired is excluded',()=>assert.equal(specials.isDiscoverable(fixture.find(x=>x.id==='e-old'),at('2026-09-21T17:00:00Z')),false));
test('future special is discoverable but scheduled',()=>{const row=fixture.find(x=>x.id==='f-future');assert.equal(specials.isDiscoverable(row,at('2026-09-21T17:00:00Z')),true);assert.equal(specials.scheduleState(row,at('2026-09-21T17:00:00Z')).key,'scheduled');});
test('multiple specials for one business remain records',()=>assert.equal(specials.forBusiness(fixture,'C',at('2026-09-21T17:00:00Z')).length,2));
test('unique business count deduplicates records',()=>assert.equal(specials.uniqueBusinessIds(fixture,at('2026-09-21T17:00:00Z')).filter(x=>x==='H').length,1));
test('record count does not deduplicate business',()=>assert.equal(specials.filter(fixture,'all',at('2026-09-21T17:00:00Z')).filter(x=>x.business_id==='H').length,2));
test('lunch filter',()=>assert.ok(specials.filter(fixture,'lunch_special',at('2026-09-21T17:00:00Z')).every(x=>x.type==='lunch_special')));
test('happy hour filter',()=>assert.ok(specials.filter(fixture,'happy_hour',at('2026-09-21T17:00:00Z')).every(x=>x.type==='happy_hour')));
test('all filter includes both types',()=>assert.deepEqual(new Set(specials.filter(fixture,'all',at('2026-09-21T17:00:00Z')).map(x=>x.type)),new Set(['lunch_special','happy_hour'])));
test('business detail lookup uses business id',()=>assert.deepEqual(specials.forBusiness(fixture,'B',at('2026-09-21T17:00:00Z')).map(x=>x.id),['b-happy']));
test('badge kinds derive from active records',()=>assert.deepEqual(specials.activeKindsForBusiness(fixture,'C',at('2026-09-21T17:00:00Z')),['lunch_special']));
test('coupon active-state contract remains unchanged',()=>assert.equal(active.isActive({id:'c',is_active:true,start_date:'2026-09-21',end_date:'2026-09-21'},'coupon',at('2026-09-22T04:59:59Z')),true));
test('event active-state contract remains unchanged',()=>assert.equal(active.isActive({id:'e',is_active:true,is_published:true,start_date:'2026-09-21',end_date:'2026-09-21'},'event',at('2026-09-22T04:59:59Z')),true));
test('benefit active-state contract remains unchanged',()=>assert.equal(active.isActive({id:'b',enabled:true,start_date:'2026-09-21',end_date:'2026-09-21'},'benefit',at('2026-09-22T04:59:59Z')),true));
test('recommendation authority output is unaffected by special fields',()=>{const rows=Array.from({length:8},(_,i)=>({id:String(i),name:`B${i}`,is_active:true,list_visible:true,paid_active:false,created_at:`2026-09-${String(10+i).padStart(2,'0')}T00:00:00Z`,specials:i?[fixture[0]]:[]}));const authority=home.create({now:()=>at('2026-09-21T12:00:00Z')});const ids=result=>Object.fromEntries(['featured','new','popular'].map(key=>[key,result[key].map(row=>row.id)]));assert.deepEqual(ids(authority.select('2026-09-21',rows)),ids(authority.select('2026-09-21',rows.map(({specials,...row})=>row))));});
test('pagination retains more than 1000 specials',async()=>{const rows=Array.from({length:1508},(_,i)=>({id:i+1,business_id:String(i%8)}));const result=await pagination.collectPages({pageSize:1000,fetchPage:({from,to})=>rows.slice(from,to+1)});assert.equal(result.rows.length,1508);assert.equal(result.complete,true);});
test('region change stale response cannot commit',async()=>{coordinator.reset();let resolveA;const commits=[];const a=coordinator.run({scope:'specials',resource:'business_specials',conditions:{region:'a'},loader:()=>new Promise(r=>{resolveA=r}),commit:v=>commits.push(v)});const b=coordinator.run({scope:'specials',resource:'business_specials',conditions:{region:'b'},loader:()=>Promise.resolve('B'),commit:v=>commits.push(v)});await b;resolveA('A');await a;assert.deepEqual(commits,['B']);});
test('CRUD payload validation accepts valid records and rejects malformed input',()=>{assert.equal(specials.validation(fixture[0]).valid,true);assert.equal(specials.validation({...fixture[0],start_time:'25:00'}).valid,false);assert.equal(specials.validation({...fixture[0],type:'coupon'}).valid,false);});
test('admin CRUD uses the signed-in Supabase client for the separate table',()=>{const source=fs.readFileSync(path.join(__dirname,'../admin/assets/admin.js'),'utf8');assert.match(source,/from\('business_specials'\)\.insert/);assert.match(source,/from\('business_specials'\)\.update/);assert.match(source,/from\('business_specials'\)\.delete/);});
test('migration grants anon read while explicitly revoking anon writes',()=>{const source=fs.readFileSync(path.join(__dirname,'../supabase/business-specials-phase1.sql'),'utf8');assert.match(source,/grant select on public\.business_specials to anon/);assert.match(source,/revoke insert,update,delete on public\.business_specials from anon/);});
for(const size of [0,1,19,20,21,40,41,1511])test(`bounded list initially renders at most 20 of ${size} records`,()=>{const rows=Array.from({length:size},(_,id)=>({id}));const batch=specials.visibleBatch(rows);assert.equal(batch.rows.length,Math.min(size,20));assert.equal(batch.total,size);assert.equal(batch.hasMore,size>20);});
test('load more advances in authoritative batches and eventually exposes all 1511 without duplicates',()=>{const rows=Array.from({length:1511},(_,id)=>({id}));let count=specials.VISIBLE_BATCH_SIZE,batch=specials.visibleBatch(rows,count);assert.equal(batch.rows.length,20);count=batch.nextCount;batch=specials.visibleBatch(rows,count);assert.equal(batch.rows.length,40);while(batch.hasMore){count=batch.nextCount;batch=specials.visibleBatch(rows,count);}assert.equal(batch.rows.length,1511);assert.equal(new Set(batch.rows.map(row=>row.id)).size,1511);});
test('filter changes retain full totals while resetting visible count to first batch',()=>{const rows=Array.from({length:60},(_,id)=>({...fixture[0],id:String(id),type:id%2?'happy_hour':'lunch_special'}));for(const type of ['all','lunch_special','happy_hour','all','lunch_special','happy_hour']){const filtered=specials.sort(specials.filter(rows,type,at('2026-09-21T17:00:00Z')),at('2026-09-21T17:00:00Z'));const batch=specials.visibleBatch(filtered,specials.VISIBLE_BATCH_SIZE);assert.equal(batch.rows.length,20);assert.equal(batch.total,type==='all'?60:30);assert.equal(new Set(batch.rows.map(row=>row.id)).size,batch.rows.length);}});
test('public renderer resets batches on filter, sorts before slice, and keeps detail independent',()=>{const source=fs.readFileSync(path.join(__dirname,'../app-v99.js'),'utf8');assert.match(source,/sort\(globalThis\.DtmRestaurantSpecials\.filter\(businessSpecials,restaurantSpecialFilter\)\)/);assert.match(source,/restaurantSpecialVisibleCount=globalThis\.DtmRestaurantSpecials\.VISIBLE_BATCH_SIZE/);assert.match(source,/visibleBatch\(rows,restaurantSpecialVisibleCount\)/);assert.match(source,/forBusiness\(businessSpecials,b\.id\)/);});
