-- TEST PROJECT ONLY. No Production rows or secrets. Supabase-managed auth/storage schemas must already exist.
begin;
create extension if not exists pgcrypto;
do $$ begin
  if to_regclass('public.businesses') is not null
     or to_regclass('public.profiles') is not null then
    raise exception 'Test setup requires a NEW empty Supabase project';
  end if;
end $$;
create table public.owner_test_project_marker(id boolean primary key default true check(id));
insert into public.owner_test_project_marker(id) values(true);
create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user', area text, created_at timestamptz not null default now()
);
create table public.businesses (
  id bigint generated by default as identity primary key,
  name_ko text not null, region text not null default 'dallas', area text,
  category_ko text, image_url text, is_active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.business_requests (
  id bigint generated by default as identity primary key,
  business_name text not null, region text not null default 'dallas',
  status text not null default 'pending', created_at timestamptz not null default now()
);
create table public.coupons (
  id bigint generated by default as identity primary key,
  business_id bigint references public.businesses(id), title text not null,
  delivery_mode text not null default 'display', coupon_code text,
  image_url text, is_active boolean not null default true,
  sort_order integer not null default 0, created_at timestamptz not null default now()
);
create table public.posts (
  id bigint generated by default as identity primary key,
  business_id bigint references public.businesses(id), type text not null,
  subtype text, title text not null, body text,
  is_active boolean not null default true, created_at timestamptz not null default now()
);
create table public.community_posts (
  id uuid primary key default gen_random_uuid(), category text not null,
  title text not null, body text not null, password_hash text not null,
  status text not null default 'approved', created_at timestamptz not null default now()
);
create table public.business_specials (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id),
  type text not null check(type in ('lunch_special','happy_hour')),
  title text not null, is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create table public.business_special_items (
  id bigint generated by default as identity primary key,
  special_id bigint not null references public.business_specials(id),
  item_name text not null, created_at timestamptz not null default now()
);
create function public.owner_test_admin_access(target_business_id bigint)
returns boolean language sql stable security definer set search_path=pg_catalog,public as $$
  select exists(select 1 from public.profiles p where p.user_id=auth.uid()
    and (p.role='super_admin' or (p.role='regional_editor' and
      p.area=(select b.region from public.businesses b where b.id=target_business_id))));
$$;
create function public.owner_test_community_create(p_title text,p_body text)
returns uuid language plpgsql security definer set search_path=pg_catalog,public as $$
declare new_id uuid;
begin
  insert into public.community_posts(category,title,body,password_hash)
  values('qna',p_title,p_body,'test-only-hash') returning id into new_id;
  return new_id;
end $$;
revoke all on function public.owner_test_community_create(text,text) from public;
grant execute on function public.owner_test_community_create(text,text) to anon,authenticated;
alter table public.profiles enable row level security;
alter table public.businesses enable row level security;
alter table public.business_requests enable row level security;
alter table public.coupons enable row level security;
alter table public.posts enable row level security;
alter table public.community_posts enable row level security;
alter table public.business_specials enable row level security;
alter table public.business_special_items enable row level security;
grant usage on schema public to anon,authenticated;
grant select,insert,update,delete,truncate on public.businesses,public.business_requests,
  public.coupons,public.posts,public.business_specials,public.business_special_items
  to anon,authenticated;
grant select on public.community_posts to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;
commit;
